<a href="https://colab.research.google.com/github/G1A021037-ANJASFEDO/Learning-TensorFlow/blob/main/Introduction_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
# Import the TensorFlow library
import tensorflow as tf


##Introduction

###Create Tensor

In [34]:
# Define a string variable
string = tf.Variable("Anjas", tf.string)

# TensorFlow variables are used to store and update mutable state during the execution of a TensorFlow program.
# In this case, 'string' is a variable initialized with the string "Anjas" and has a data type of tf.string.

# Define an integer variable
number = tf.Variable(20, tf.int32)

# Similarly, 'number' is a variable initialized with the integer value 20 and has a data type of tf.int32.

# Define a floating-point variable
floats = tf.Variable(20.1, tf.float32)

# 'floats' is a variable initialized with the floating-point value 20.1 and has a data type of tf.float32.

# TensorFlow variables allow for dynamic updates during training or execution of a model.


###Rank/Degree

In [35]:
# Define a rank-1 tensor (vector) with string elements
rank1_tensor = tf.Variable(["A", "B", "C"], tf.string)

# 'rank1_tensor' is a one-dimensional tensor (vector) initialized with string elements "A", "B", and "C".
# The data type of the tensor is tf.string.

# Define a rank-2 tensor (matrix) with string elements
rank2_tensor = tf.Variable([["A", "B", "C"], ["D", "E", "F"]], tf.string)

# 'rank2_tensor' is a two-dimensional tensor (matrix) initialized with string elements in two rows and three columns.
# The data type of the tensor is tf.string.

# Check the rank of the rank-2 tensor
tensor_rank = tf.rank(rank2_tensor)

# 'tf.rank()' is used to determine the rank of a tensor, which represents the number of dimensions in the tensor.

# Print the tensor rank
print("Rank of rank2_tensor:", tensor_rank.numpy())

# The rank of 'rank2_tensor' is then printed to the console using the 'numpy()' method to extract the rank value.


Rank of rank2_tensor: 2


###Shape of Tensor

In [36]:
# Access the shape of the rank-2 tensor
tensor_shape = rank2_tensor.shape

# 'rank2_tensor.shape' is used to retrieve the shape of the tensor, which represents the size of each dimension.

# Print the tensor shape
print("Shape of rank2_tensor:", tensor_shape)

# The shape of 'rank2_tensor' is then printed to the console.

# Note: In TensorFlow, the shape is represented as a TensorShape object, which provides methods to access dimensions.


Shape of rank2_tensor: (2, 3)


###Change Shape

In [37]:
# Create a rank-3 tensor filled with ones
tensor1 = tf.ones([1, 2, 3])

# 'tensor1' is initialized as a rank-3 tensor (a 3D tensor) filled with ones.
# The shape of 'tensor1' is [1, 2, 3], representing one element along the first dimension, two along the second, and three along the third.

# Reshape 'tensor1' to a new shape [2, 3, 1]
tensor2 = tf.reshape(tensor1, [2, 3, 1])

# 'tf.reshape()' is used to change the shape of a tensor. In this case, 'tensor1' is reshaped to a new shape of [2, 3, 1].
# The total number of elements remains the same after reshaping.

# Reshape 'tensor2' to a new shape [3, -1]
tensor3 = tf.reshape(tensor2, [3, -1])

# Reshaping 'tensor2' to [3, -1] means that the size of the second dimension is inferred to make the total number of elements equal to the original tensor.
# The '-1' is a placeholder that automatically calculates the size based on the other dimensions.

# Print the original and reshaped tensors
print("Original tensor:", tensor1)
print("Reshaped tensor (tensor2):", tensor2)
print("Reshaped tensor (tensor3):", tensor3)


Original tensor: tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
Reshaped tensor (tensor2): tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
Reshaped tensor (tensor3): tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


###Type of Tensor

- Variable
- Constant
- Placeholder
- SparseTensor
except Variable, all of Tensor Type is immuttable

###Evaluating Tensor

In [38]:
# Convert the TensorFlow tensor 'tensor2' to a NumPy array
result = tensor2.numpy()

# TensorFlow tensors can be converted to NumPy arrays using the 'numpy()' method. This allows interoperability between TensorFlow and NumPy.

# Print the NumPy array
print(result)


[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


##Reshape Tensor

In [39]:
# Check TensorFlow version
print("TensorFlow version:", tf.__version__)

# Print the version of TensorFlow to ensure compatibility and access to latest features.


TensorFlow version: 2.14.0


In [40]:
# Uncomment one of the following sections at a time to run it.

# Option 1: Create a tensor filled with ones
# t = tf.ones()

# Option 2: Create a tensor filled with zeros with shape [5, 5, 5, 5]
t = tf.zeros([5, 5, 5, 5])

# 't' is initialized as a rank-4 tensor (4D tensor) filled with zeros. The shape of 't' is [5, 5, 5, 5].

# Reshape 't' to a new shape [125, -1]
t = tf.reshape(t, [125, -1])

# Reshaping 't' to [125, -1] means that the size of the second dimension is inferred to make the total number of elements equal to the original tensor.
# The '-1' is a placeholder that automatically calculates the size based on the other dimensions.

# Print the reshaped tensor
print(t)


tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]