<a href="https://colab.research.google.com/github/G1A021037-ANJASFEDO/Learning-TensorFlow/blob/main/Introduction_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

##Introduction

###Create Tensor

In [ ]:
string = tf.Variable("Anjas", tf.string)
number = tf.Variable(20, tf.int32)
floats = tf.Variable(20.1, tf.float32)

###Rank/Degree

In [ ]:
rank1_tensor = tf.Variable(["A", "B", "C"], tf.string)
rank2_tensor = tf.Variable([["A", "B", "C"], ["D", "E", "F"]], tf.string)

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

###Shape of Tensor

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])

###Change Shape

In [ ]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


###Type of Tensor

- Variable
- Constant
- Placeholder
- SparseTensor
except Variable, all of Tensor Type is immuttable

###Evaluating Tensor

In [ ]:
result = tensor2.numpy()

print(result)

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
