<a href="https://colab.research.google.com/github/Anjasfedo/Learning-TensorFlow/blob/main/eat_tensorflow2_in_30_days/Chapter2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-1 Data Structure

Program = Data Structure = Algorithm

Tensorflow Program = Data Structure of Tensor + Algorithm in Graph

Tensor & Graph are key concepts of TensorFlow

The Fundamental data structure in TensorFlow is Tensor, which is multi-dimentional array. Tensor is simmilar with the `array` in NumPy

There are thow types of tensor according to the behavior
1. `constant` cannot be re-assigned in the graph
2. `variable` can be re-assigned through operator such as `assign`

## 1. Constant Tensor

The data type of tensor is basically coresponding to numpy.array

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
i = tf.constant(1) # tf.int32 type constant
i

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
l = tf.constant(1, dtype=tf.int64) # tf.int64 type constant
l

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [5]:
f = tf.constant(1.23) # tf.float32 type constant
f

<tf.Tensor: shape=(), dtype=float32, numpy=1.23>

In [6]:
d = tf.constant(3.14, dtype=tf.double) # tf.double type constant
d

<tf.Tensor: shape=(), dtype=float64, numpy=3.14>

In [7]:
s = tf.constant('hello') # tf.string type constant
s

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [8]:
b = tf.constant(True) # tf.bool type constant
b

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [16]:
print(tf.int64 == np.int64)
print(tf.float32 == np.float32)
print(tf.double == np.float64)

True
True
True


Each data type can be represet by tensor in different rank

- Scalars are tensors with rank 0
- Arrays ate with rank 1
- Matrix are with rank 2
- Colorful image has three channels (RGB), which can be represented as a tensor with rank 3
- There is a temporal dimension for video so it could be represent as a rank 4 tensor

An intuitive way to understand: the number of the square branckets equals to the rank of the tensor

In [17]:
scalar = tf.constant(True) # a scalar is rank 0 tensor

print(tf.rank(scalar))
print(scalar.numpy().ndim) # tf.rank is equal to the ndim funcion in numpy

tf.Tensor(0, shape=(), dtype=int32)
0


In [19]:
vector = tf.constant([1, 2, 3]) # a vector is rank 1 tensor

print(tf.rank(vector))
print(np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32)
1


In [21]:
matrix = tf.constant([[1, 2], [3, 4]]) # a matrix is rank 2 tensor

print(tf.rank(matrix).numpy())
print(np.ndim(matrix))

2
2


In [22]:
tensor3 = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # a tensor3 is rank 3 tensor

print(tf.rank(tensor3).numpy())
print(np.ndim(tensor3))

3
3


In [23]:
tensor4 = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]) # a tensor4 is rank 4 tensor

print(tf.rank(tensor4).numpy())
print(np.ndim(tensor4))

4
4


Use `tf.cast` to change the data type of the tensor

The method `numpy()` is for converting the data type from tensor to numpy array

The method `shape` is for checking up the size of tensor

In [24]:
h = tf.constant([123, 456], dtype=tf.int32)
h

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([123, 456], dtype=int32)>

In [25]:
f = tf.cast(h, dtype=tf.float32)
f

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([123., 456.], dtype=float32)>

In [27]:
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>


In [29]:
y = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print(y.numpy())
print(y.shape)

[[1. 2.]
 [3. 4.]]
(2, 2)


In [30]:
u = tf.constant(u'Hello World')

print(u.numpy())
print(u.numpy().decode('utf-8'))

b'Hello World'
Hello World


## 2. Variable Tensor

The trainable parameters in the models are usually defined as varaibles

In [31]:
# The value of constant is NOT CHANGABLE. re-assignment creates a new space in the memory
c = tf.constant([1.0, 2.0])

print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
136333294625968


In [34]:
c = c + tf.constant([1.0, 1.0])

print(c)
print(id(c))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
136336331346464


In [35]:
# The value of a varaible is changable through re-assigning methods such as assign, assign_add, etc
v = tf.Variable([1.0, 2.0], name='v')

print(v)
print(id(v))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
136333293273584


In [37]:
v.assign_add([1.0, 1.0])

print(v)
print(id(v))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
136333293273584
